// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db_sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID        uuid.UUID
	Name      string
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Logo        uuid.NullUUID
	Workspace   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type TenantFile struct {
	ID        uuid.UUID
	Name      string
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	Password     sql.NullString
	Name         string
	CreatedAt    time.Time
	LastActiveAt time.Time
	DeletedAt    sql.NullTime
}

type UserLookup struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Email    string
}
